name: CI-CD - Tests and Publishing
on:
  push:
    branches:
    - main
  pull_request: {}
  workflow_dispatch:
    inputs:
      publish:
        description: Trigger with publish
        required: false
        type: boolean
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test_vector-expr:
    name: 'Test vector_expr: vector-expr'
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust-test.yml@v2
    needs: []
    if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    with:
      working_directory: .
      test_publish_required: 'true'
    secrets: inherit
  publish_vector-expr:
    name: 'Publish vector_expr: vector-expr'
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust-build.yml@v2
    needs:
    - test_vector-expr
    if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.publish)) }}
    with:
      skip_test: 'false'
      publish: 'true'
      publish_private_registry: 'false'
      publish_public_registry: 'true'
      publish_docker: 'false'
      publish_binary: 'false'
      publish_npm_napi: 'false'
      working_directory: .
    secrets: inherit
