on:
  pull_request:

name: Test on PR

jobs:
  test-fse-app:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust-test.yml@v1.0.0
    with:
      private-registry-host: ssh.shipyard.rs
      private-registry-name: foresight-mining-software-corporation
      initial_event_name: ${{ github.event_name }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      private-registry-private-key: ${{ secrets.CARGO_PRIVATE_REGISTRY_SSH_PRIVATE_KEY }}
      private-registry-token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}